sudo: required
services:
  - docker

before_install:
  - docker build -t jstuck/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true jstuck/react-test npm test 

after_success:
  # build images
  - docker build -t jstuck/multi-client ./client
  - docker build -t jstuck/multi-nginx ./nginx
  - docker build -t jstuck/multi-server ./server
  - docker build -t jstuck/multi-worker ./worker
  
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push jstuck/multi-client
  - docker push jstuck/multi-nginx
  - docker push jstuck/multi-server
  - docker push jstuck/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker-react
  env: MultiDockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-081177934285
  bucket_path: docker-multi-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY